In [45]:
import numpy as np
from sklearn import datasets
import random
from sklearn.linear_model import SGDRegressor
from sklearn.model_selection import train_test_split

In [190]:
# iris = datasets.load_iris()
# X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2)
X = 2 * np.random.rand(100, 1)
y = 4 + 3 * X + np.random.randn(100, 1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
X.shape, y.shape

((100, 1), (100, 1))

In [272]:
n_epochs = 300
t0, t1 = 5, 50  # learning schedule hyperparameters

def learning_schedule(t):
    return t0 / (t + t1)

def f(X, y, s):
    X_b = np.c_[np.ones((len(X), 1)), X]  # Add bias term
    theta = np.random.rand(X_b.shape[1], 1)  # Initialize theta
    m = X_b.shape[0]
    for epoch in range(n_epochs):
        for i in range(m):
            random_subset_indices = random.sample(range(1, X_b.shape[1]), 1)  # Exclude bias term
            random_gradient = np.zeros((X_b.shape[1], 1))
            for j in random_subset_indices:
                random_gradient[j] = (2/m) * X_b[:, j].T.dot(X_b.dot(theta) - y)
            theta -= 0.01 * random_gradient
    return theta

f(X, y, 1)

array([[0.10270818],
       [6.03968307]])

In [195]:
n_epochs = 50
t0, t1 = 5, 50  # learning schedule hyperparameters

def learning_schedule(t):
    return t0 / (t + t1)

def MySGD(X, y, a, s):
    X_b = np.c_[np.ones((len(X),1)), X]
    theta = np.random.rand(X_b.shape[1], 1)
    m = X_b.shape[0]
    for epoch in range(n_epochs):
        for i in range(m):
            to_update = random.sample(range(m), s)
            
            msa = 2*(X_b[to_update].T.dot(X_b[to_update].dot(theta)-y[to_update]))
            eta = learning_schedule(epoch * m + i)
            theta = theta - eta*msa
    return theta
MySGD(X, y, 0.0001, 1)

array([[4.30222374],
       [2.96500334]])

In [137]:
om = SGDRegressor(alpha=0.0001)
om.fit(X_train, y_train.ravel())

SGDRegressor()

In [138]:
om.coef_, om.intercept_

(array([3.32550029]), array([3.60541296]))

In [76]:
# to_update = random.sample(range(theta.shape[0]), 2)


array([0, 0])